name: quantum-radar

on:
  schedule: [ { cron: '17 * * * *' } ]
  push: { branches: [ main, master ] }

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Radar
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SEC_USER_AGENT: ${{ secrets.SEC_USER_AGENT }}
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          python -m src.main

      - name: Commit dashboard data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data.json docs/signals.json data/state.json || true
          git commit -m "Update radar data" || echo "No changes"
          git push
